#!/bin/bash
this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source /opt/ros/melodic/setup.bash
source $this_dir/software/gcs/devel/setup.bash
roslaunch mavros px4.launch fcu_url:="udp://:14540@localhost:14557" &
cd $this_dir/simulation/Firmware/

make posix_sitl_default gazebo  -j4 
