#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import rospy
import std_msgs.msg
from std_msgs.msg import Bool
from std_msgs.msg import Int64

class dock_node:

    WAIT_TIME = 8.0

    def __init__(self):

        self.request_time = 0.0
        self.request = False
        self.payload = False

        rospy.init_node('dock_node', anonymous=True)

        # Subscribers
        rospy.Subscriber("docklink/statusRequest",
                         Bool,
                         self.request_callback,
                         queue_size=1)

        # Publishers
        self.status_pub = rospy.Publisher(
            "docklink/statusPublish",
            Int64,
            queue_size=1)

    def request_callback(self, msg):
        if not self.request:
            self.request_time = rospy.get_time()
        self.request = True
        self.payload = not self.payload
        return


    def run(self):
        rate = rospy.Rate(1)
        while not rospy.is_shutdown():
            now = rospy.get_time()
            if now > self.request_time + self.WAIT_TIME and self.request:
                if self.payload:
                    self.status_pub.publish(1)
                else:
                    self.status_pub.publish(2)
                self.request = False
            rate.sleep()
        return


if __name__ == '__main__':
    dock_node = dock_node()
    dock_node.run()
