set(_CATKIN_CURRENT_PACKAGE "drone_decon")
set(drone_decon_VERSION "0.0.0")
set(drone_decon_MAINTAINER "Kasper Hoej lorenzen <kasper.lorenzen@gmail.com>")
set(drone_decon_PACKAGE_FORMAT "1")
set(drone_decon_BUILD_DEPENDS "roscpp" "std_msgs" "mavlink_lora")
set(drone_decon_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "std_msgs")
set(drone_decon_BUILDTOOL_DEPENDS "catkin" "message_generation")
set(drone_decon_BUILDTOOL_EXPORT_DEPENDS )
set(drone_decon_EXEC_DEPENDS "message_runtime" "roscpp" "std_msgs")
set(drone_decon_RUN_DEPENDS "message_runtime" "roscpp" "std_msgs")
set(drone_decon_TEST_DEPENDS )
set(drone_decon_DOC_DEPENDS )
set(drone_decon_URL_WEBSITE "")
set(drone_decon_URL_BUGTRACKER "")
set(drone_decon_URL_REPOSITORY "")
set(drone_decon_DEPRECATED "")