#!/usr/bin/env python3
"""
Dronelink node. Inits a node and imports main script
"""
# Third-party libraries
import rospy
# Local libraries
from dronelink import dronelink


if __name__ == "__main__":
    rospy.init_node("dronelink")
    dronelink.main()
